export const QUEUE_TYPES = Object.freeze({
    USER_QUEUE: "USER_QUEUE",
    USER_REGISTERED: "USER_REGISTERED",
    USER_UPDATED: "USER_UPDATED",
    USER_DELETED: "USER_DELETED",

    ORDER_CREATED: "ORDER_CREATED",
    ORDER_UPDATED: "ORDER_UPDATED",
    ORDER_CANCELLED: "ORDER_CANCELLED",

    PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
    PAYMENT_FAILED: "PAYMENT_FAILED",

    PRODUCT_CREATED: "PRODUCT_CREATED",
    PRODUCT_UPDATED: "PRODUCT_UPDATED",
    PRODUCT_DELETED: "PRODUCT_DELETED",
    PRODUCT_BACK_IN_STOCK: "PRODUCT_BACK_IN_STOCK",

    INVENTORY_UPDATED: "INVENTORY_UPDATED",
    LOW_STOCK: "LOW_STOCK",

    NOTIFICATION_CREATED: "NOTIFICATION_CREATED",
    EMAIL_SEND: "EMAIL_SEND",
    SMS_SEND: "SMS_SEND",
    PUSH_SEND: "PUSH_SEND",

    ANALYTICS_TRACK: "ANALYTICS_TRACK",
});