@BASE_URL = http://localhost:5500/api/v1/user
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTk4YmJmYzIyZTFhYmY3NzE2NDdjMzIiLCJyb2xlIjoiNmE5NmIwZDg0ZTBhMDU0Mjc5ZjBmM2M4IiwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTc4ODM5NDYwNiwiZXhwIjoxNzg5Mjk0NjA2fQ.yclkv6AF7NhNki_yAFnluvj65PDT5RXKTHfq60VDOyQ


### Assign Role to User
PATCH {{BASE_URL}}/assign-role 
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "userId": "6a98bce0dbf2e02c3faa161c",
  "roleId": "6a96b1114e0a054279f0f3d0"
}