@BASE_URL = http://localhost:5500/api/v1/rbac/permissions
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTk4YmJmYzIyZTFhYmY3NzE2NDdjMzIiLCJyb2xlIjoiNmE5NmIwZDg0ZTBhMDU0Mjc5ZjBmM2M4IiwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTc4ODM5NzA2MywiZXhwIjoxNzg5Mjk3MDYzfQ.TH-6yj9pqEqzqPRwQF3ionaeFxuLA0eO9sJDoPLYc5w
@REFRESH_TOKEN = 1


### Create Permission
POST {{BASE_URL}}/
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "name": "Role Update",
  "resource": "role",
  "description": "Permission to update role",
  "action": "update"
}


### Get All Permissions
GET {{BASE_URL}}/
Content-Type: application/json
Authorization: Bearer {{TOKEN}}


### Get All Permissions By Resource
GET {{BASE_URL}}/category
Content-Type: application/json



### Get Permission By Key
GET {{BASE_URL}}/permission
Content-Type: application/json

{
  "permissionKey":"product:create"
}