@BASE_URL = http://localhost:5000/api/v1/auth
@TOKEN = 1

### Register User
POST {{BASE_URL}}/register
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "don",
  "phoneNumber": "+6145",
  "email": "ul4@gmail.com",
  "password": "Password123!"
}

### Login user

POST {{BASE_URL}}/login 
Content-Type: application/json

{
  "email": "grishma@example.com",
  "password": "Password123"
}